version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=WARNING
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
    networks:
      - api_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=api_consulta_v2
    volumes:
      - mongo_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - api_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - api_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis
    networks:
      - api_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command: /bin/sh -c "mkdir -p /etc/prometheus && prometheus --config.file=/etc/prometheus/prometheus.yml"
    networks:
      - api_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - api_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

volumes:
  mongo_data:
  redis_data:
  grafana_data:

networks:
  api_network:
    driver: bridge
