global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus próprio - configuração especial para VPS com route-prefix
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/prometheus/metrics'  # Corrigido para incluir route-prefix
    scrape_interval: 15s

  # API Consulta v2
  - job_name: 'api-consulta-v2'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Traefik Gateway
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (comentado - não disponível em produção)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['host.docker.internal:9100']
  #   scrape_interval: 30s
